trigger: none

parameters:
- name: RELEASE_TAG
  displayName: Release tag
  type: string
  default: false

pool:
  name: Leanware Kampus testi

steps:
- checkout: self
- checkout: git://Kampus/tuni-kpj-auth

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
- task: Docker@2
  displayName: Leanware Docker registry login
  inputs:
    containerRegistry: 'Leanware Docker registry'
    command: 'login'

- task: Docker@2
  displayName: Build Docker image
  inputs:
    containerRegistry: 'Leanware Docker registry'
    repository: 'lw/tau/tuni-kpj'
    command: 'build'
    Dockerfile: 'tuni-kpj/Dockerfile'
    arguments: |
      --build-arg NODE_CONFIG_ENV=tau
      --build-arg GIT_SHA=$(Build.SourceVersion)
    tags: |
      ${{ parameters.RELEASE_TAG }}

- task: Docker@2
  displayName: Push Docker image to Leanware registry
  inputs:
    containerRegistry: 'Leanware Docker registry'
    repository: 'lw/tau/tuni-kpj'
    command: 'push'
    tags: |
      ${{ parameters.RELEASE_TAG }}
- task: Bash@3
  displayName: Pull new image from Leanware registry
  inputs:
   targetType: 'inline'
   script: |
     docker pull hub.leanware.fi/lw/tau/tuni-kpj:${{ parameters.RELEASE_TAG }}
   failOnStderr: true
- task: Bash@3
  displayName: Push new release to AWS
  inputs:
   targetType: 'inline'
   script: |
     aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 947561294603.dkr.ecr.eu-north-1.amazonaws.com/lw2tau
     docker tag hub.leanware.fi/lw/tau/tuni-kpj:${{ parameters.RELEASE_TAG }} 947561294603.dkr.ecr.eu-north-1.amazonaws.com/lw2tau/tuni-kpj:${{ parameters.RELEASE_TAG }}
     docker push 947561294603.dkr.ecr.eu-north-1.amazonaws.com/lw2tau/tuni-kpj:${{ parameters.RELEASE_TAG }}
   failOnStderr: false
- task: Bash@3
  displayName: Remove folders from the agent
  inputs:
   targetType: 'inline'
   script: |
     echo rm -rf -- ..?* .[!.]* *
   failOnStderr: true