trigger:
- development

pool:
  name: Leanware Kampus testi

steps:
- task: Docker@2
  displayName: Leanware Docker registry login
  inputs:
    containerRegistry: 'Leanware Docker registry'
    command: 'login'
- task: Docker@2
  displayName: Build Docker image
  inputs:
    containerRegistry: 'Leanware Docker registry'
    repository: 'lw/tau/tuni-kpj'
    command: 'build'
    Dockerfile: 'Dockerfile'
    arguments: |
      --build-arg NODE_CONFIG_ENV=tau
      --build-arg GIT_SHA=$(Build.SourceVersion)
    tags: |
      latest
- task: Docker@2
  displayName: Push Docker image to Leanware registry
  inputs:
    containerRegistry: 'Leanware Docker registry'
    repository: 'lw/tau/tuni-kpj'
    command: 'push'
    tags: |
      latest
- task: Bash@3
  displayName: Pull new image from Leanware registry
  inputs:
   targetType: 'inline'
   script: |
     docker pull hub.leanware.fi/lw/tau/tuni-kpj
   failOnStderr: true
- task: Bash@3
  displayName: Restart containers
  inputs:
   targetType: 'inline'
   script: |
     cd /home/leanware/tuni-kpj
     ./stop_containers.sh
     ./start_containers.sh
   failOnStderr: false
- task: Bash@3
  displayName: Remove folders from the agent
  inputs:
   targetType: 'inline'
   script: |
     rm -rf -- ..?* .[!.]* *
   failOnStderr: true