version: '3.5'

services:
  app:
    build:
      context: .
      args:
        - JEST=true
        - E2E=true
    command: ['npm','run', 'start:test']
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 8000:8000
    container_name: palaute_app_test

  db:
    image: registry.toska.cs.helsinki.fi/palaute_test_db
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: palaute_test_db
