version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: palaute_dev
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?targetServerType=primary
      - REDIS_HOST=redis
      - JAMI_HOST=jami
      - JAMI_PORT=3003
      - JWT_KEY=minttujam
      - NODE_CONFIG_ENV=hy
      - UPDATER_URL=http://updater:3000
    ports:
      - 3000:3000
      - 9229:9229
    container_name: palaute_app_test

  db:
    image: postgres:15.4
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/data
    container_name: palaute_test_db

  jami:
    image: quay.io/toska/jami:production
    environment:
      - PORT=3003
      - NODE_ENV=dev
      - DATABASE_URL=postgres://postgres:postgres@jami-db:5432/postgres
    ports:
      - 3003:3003
    container_name: jami

  jami-db:
    image: postgres:13.2
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: jami-db

volumes:
  pg_data: