name: Feature branches & pull requests

on:
  pull_request:
    types: [opened]
  push:
    branches-ignore:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  run-tests:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v5
  
      - name: Echo confirmation
        run: echo "Tests run" 

