name: Feature branches & pull requests

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    if: ${{ github.actor != 'renovate[bot]' }}
    uses: ./.github/workflows/test.yml
    secrets: inherit

  run-tests:
    if: ${{ github.actor != 'renovate[bot]' }}
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Echo confirmation
        run: echo "Tests run"
