name: E2E Tests

on: [workflow_call]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build project for eslint
        run: npm ci
      - name: Run eslint
        run: npm run lint

  cypress:
    strategy:
      fail-fast: false
      matrix:
        spec:
          [
            common,
            continuousFeedback,
            courseSummary,
            emailStatsView,
            interimFeedback,
            organisationSurvey,
            programme,
            teacherview,
            universitySurvey,
            userfeedbacks,
          ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: npm ci
        run: npm ci --no-audit --no-fund

      - name: Login to toska docker registry
        uses: docker/login-action@v3
        with:
          registry: registry-toska.ext.ocp-prod-0.k8s.it.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}

      - name: Start the application
        run: docker compose -f docker-compose.ci.yml up -d

 
      - name: Run cypress tests with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 6
          max_attempts: 2
          command: ./node_modules/.bin/cypress run --headless --browser chrome --spec "cypress/integration/${{ matrix.spec }}.spec.js"

      - name: Upload video
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          path: /home/runner/work/palaute/palaute/cypress/videos/*

      - name: Check logs
        run: docker compose -f docker-compose.ci.yml logs
        if: failure()
